Autohire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('user/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls')),

    path('create_resume/', include('create_resume.urls', namespace='create_resume'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('login/', views.log_in, name='log_in'),
    path('candidate_register/', views.candidate_sign_up, name='candidate_sign_up'),
    path('employer_register/', views.employer_sign_up, name='employer_sign_up'),
    path("logout/", views.Log_Out, name="logout"),
]

blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import addblog,home_screen_view,detail_blog_view

urlpatterns = [
    path('post/', addblog,name="addblog"),
    path('allblog/',home_screen_view,name="allblog"),
    path('allblog/<pk>', detail_blog_view, name="detailblog"),
] 

create_resume/urls.py
from django.urls import path
from . import views
from .views import (
    IdentityUpdateView,
    # create
    QualificationsCreateView,
    ExperienceCreateView,
    InternshipCreateView,
    CertificationsCreateView,
    ProjectsCreateView,
    Technical_skillsCreateView,
    # delete
    ExperienceDeleteView,
)

app_name = 'create_resume'
urlpatterns = [
    path('resume/',views.resume, name='resume'),
    path('identity-update/', IdentityUpdateView.as_view(), name='update-identity'),
    
    # create
    path('create-qualifications/', QualificationsCreateView.as_view(), name='create-qualifications' ),
    path('create-experience/', ExperienceCreateView.as_view(), name='create-experience' ),
    path('create-internship/', InternshipCreateView.as_view(), name='create-internship'),
    path('create-certification/', CertificationsCreateView.as_view(), name='create-certifications'),
    path('create-project/', ProjectsCreateView.as_view(), name='create-projects'),
    path('create-technical-skill/', Technical_skillsCreateView.as_view(), name='create-technical-skills'),
    
    #delete
    path('delete-experience/<int:pk>', ExperienceDeleteView.as_view(), name='delete-experience')
] 

home/urls.py
from django.urls import path
from . import views
from .views import (JobCreateView, filter_jobs,)

app_name='home'
urlpatterns = [
    
    # home page
    path('', views.home_page, name='home_page'),
    # test 
    path('test/', views.index, name='index'),
    
    # form to create new jobs
    path('add_job/', JobCreateView.as_view(), name='addJob'),
    
    # search for jobs based on location and position
    path('filter_jobs/', views.filter_jobs, name='filter_jobs'),
    
    # view jobs 
    path('view_jobs/', views.viewJobs, name='viewJobs'),
    
    # brief detail of a job
    path('job_detail/<int:pk>', views.jobDetail, name='jobDetail'),
    
    # applying for job
    path('apply_for_job/<int:pk>', views.apply_for_job, name="apply_for_job"),
    
    # history of jobs applied for
    path('job_applications/', views.application_view, name='application_view'),
    
    # detail view of applied job applications
    path('applied_jobdeatils_view/<int:pk>/', views.applied_jobdeatils_view, name='applied_jobdeatils_view'),
    
    # list of candidate's appplications for a job
    path('candidates_applications/', views.recieve_candidates_applications, name="candidates_applications_view"),
    
    # update job applications status for both candidate and employer
    path('update_status/<int:pk>', views.update_status, name='update_status'),
    
    # view resume of candidates applied for the job
    path('media/<int:pk>', views.open_resume, name='open_resume')
    
    # path('update_status/<int:pk>', views.update_status_reject, name='update_status_reject'),
    
    # path('saved_jobs<int:pk>/', views.save_jobs, name='savedJobs'),
    
]

home/models.py
from typing import Match
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
# Create your models here.

class Job(models.Model):
    jobType = (('','Choose job-type:'),
               ('Internship','Internship'),
               ('Part-Time','Part-Time'),
               ('Full-time','Full-time'),
    )
    position = models.CharField(max_length=200, null=False)
    company = models.CharField(max_length=200, null=False)
    start_date = models.CharField(max_length=200, null=False)
    job_type = models.CharField(max_length=50, null=False, choices=jobType)
    package = models.CharField(max_length=200, null=False)
    apply_by = models.CharField(max_length=200, null=False)
    location = models.CharField(max_length=200, null=True)
    about_company = models.TextField(max_length=1500, null=False)
    job_description = models.TextField(max_length=1500, null=False)
    eligibility = models.TextField(max_length=500, null=False)
    perks = models.TextField(max_length=500, null=False)
    openings = models.IntegerField( null=False)
    # is_applied = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.position
    
    def get_absolute_url(self):
        return reverse("home:jobDetail", kwargs={"pk": self.pk})

class Resume(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200 , null=False)
    last_name = models.CharField(max_length=200, null=False)
    mobile = models.CharField(max_length=13, null=False, default="+91")
    resume = models.FileField( upload_to='resume/', null=True)
    address = models.CharField(max_length=300, null=True)
    
class Apply_for_job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE) #error
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    position = models.CharField(max_length=200, null=False)
    company = models.CharField(max_length=200, null=False)
    start_date = models.CharField(max_length=200, null=False)
    job_type = models.CharField(max_length=50, null=False)
    package = models.CharField(max_length=200, null=False)
    apply_by = models.CharField(max_length=200, null=False)
    applied_by = models.CharField(max_length=200, null=True)
    status = models.CharField(max_length=20, null=True, blank=True)
    
    # def __str__(self):
    #     return self.job.position
    
    def get_absolute_url(self):
        return reverse("home:application_view", kwargs={"pk": self.pk})

    
    
class Recieve_job_applications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    apply_for_job = models.ForeignKey(Apply_for_job, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, null=False)
    last_name = models.CharField(max_length=200, null=False)
    mobile = models.CharField(max_length=200, null=False)
    email = models.CharField(max_length=200 ,null=False)
    position = models.CharField(max_length=200, null=True)
    applied_by = models.CharField(max_length=200, null=True)
    resume_file = models.FileField(null=True)
    status = models.CharField(max_length=20, null=True, blank=True)
    job_created_by = models.CharField(max_length=200, null=True)
    
    def get_absolute_url(self):
        return reverse("home:candidates_applications_view", kwargs={"pk": self.pk})
    
    def get_resume_url(self):
        return reverse("home:open_resume", kwargs={'pk':self.pk})
    
    
# class Create_resume(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     # personal information
#     name = models.CharField(max_length=50, null=False)
#     email = models.EmailField(null=False)
#     phone_number = models.CharField(max_length=13, null=False)
#     address = models.CharField(max_length=300, null=False)
#     # qualifications
#         # graduation
#     university_name = models.CharField(max_length=100, null=False)
#     university_location = models.CharField(max_length=200, null=False)
#     degree = models.CharField(max_length=100, null=False)
#     branch = models.CharField(max_length=200, null=False)
#     degree_duration = models.DurationField(null=False)
#         # high school
#     school_name = models.CharField(max_length=200, null=False)
#     school_location = models.CharField(max_length=200, null=False)
#     class_name = models.CharField(max_length=200, null=False)
#     branch = models.CharField(max_length=200, null=False)
#     class_duration = models.DurationField(null=False)
#     # Certifications
    
    
    
# class Employer(models.Model):
#     user=models.OneToOneField(User,null=True,on_delete=models.CASCADE)
#     name=models.CharField(max_length=200,null=True)
#     position=models.CharField(max_length=200,null=True)
#     description=models.CharField(max_length=2000,null=True)
#     salary=models.IntegerField(null=True)
#     experience=models.IntegerField(null=True)
#     Location=models.CharField(max_length=2000,null=True)
#     profile = models.CharField(max_length=200)
#     def __str__(self):
#         return self.name
    
# class Candidate(models.Model):
#     category=(
#         ('Male','male'),
#         ('Female','female'),
#         ('Other','other'),
#     )
#     name=models.CharField(max_length=200,null=True)
#     dob=models.DateField(null=True)
#     gender= models.CharField(max_length=200,null=True,choices=category)
#     mobile= models.CharField(max_length=200,null=True)
#     email= models.CharField(max_length=200,null=True)
#     resume=models.FileField(null=True)
#     company=models.ManyToManyField(Employer,blank=True)
#     profile = models.CharField(max_length=200, default="Candidate")
#     def __str__(self):
#         return self.name

home/views.py
import os
from django.db import models
from django.http import request
from django.http import response
from django.http.response import FileResponse, Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView
from django.contrib import messages
from home.admin import resume
from django.db.models import Q
# from django.contrib.auth.mixins import LoginRequiredMixin

from home.models import Apply_for_job, Job, Recieve_job_applications, Resume

# Create your views here.
def home_page(request):
    position=" "
    location=" "
    context={}
    user = request.user
    context['user']=user
    if request.GET:
        position=request.GET['positionq']
        location=request.GET['locationq']
        print('position',position)
        print('location',location)
        context[position]=str(position)
        context[location]=str(location)
        # context['query']=str(query)
        jobs_feed=Job.objects.filter(Q(position=position) | Q(position__icontains=position) | Q(location=location) | Q(location__icontains=location)).order_by('location')
        print(jobs_feed)
        context['jobs']=jobs_feed
        return render(request,'home/home.html',context)  

    jobs_feed = Job.objects.all()      
    context['jobs']=jobs_feed

    return render(request, 'home/home.html', context)

def index(request):
    job = Job.objects.all()
    userr = request.POST.get('first_name')
    user = request.user
    # recieve = Recieve_job_applications.objects.get()
    context = {
        'job':job,
        'userr':userr,
        'user':user
    }
    
    return render(request, 'home/test.html', context)


class JobCreateView(CreateView):
    model = Job
    fields = ['position', 'company', 'job_type', 'start_date', 'package', 'apply_by', 'location', 'about_company', 'job_description', 'eligibility', 'perks', 'openings', 'created_by']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)
    
def filter_jobs(request):
    position = request.POST.get('position')
    location = request.POST.get('location')
    job = Job.objects.filter(position=position, location=location)
    return render(request, 'home/home.html', {'jobs':job})

def viewJobs(request):
    job = Job.objects.filter(created_by=request.user)
    return render(request, 'home/jobs.html', {'job':job})
    
def jobDetail(request, pk):
    job = Job.objects.get(pk=pk)
    # applied = getattr(job, 'is_applied')
    id = pk
    context={
        'job':job,
        'id':id,
    }
    return render(request, 'home/job_detail.html', context)

def apply_for_job(request, pk):
    user = request.user
    resume = Resume.objects.get(user=user)
    job = get_object_or_404(Job, pk=pk)
    jobb = Job.objects.filter(pk=pk)
    position = getattr(job,'position')
    company = getattr(job,"company")
    start_date = getattr(job,"start_date")
    package = getattr(job,"package")
    apply_by = getattr(job,"apply_by")
    job_type = getattr(job,"job_type")
    job_created_by = getattr(job, 'created_by')
    applied_by = request.user 
    mobile = getattr(resume, 'mobile')
    first_name = getattr(user, "first_name")
    last_name = getattr(user, 'last_name')
    email = getattr(user, 'email')
    resumee = getattr(resume, 'resume')
    
    apply_for_job = Apply_for_job.objects.create(user=request.user, job=job, resume=resume, position= position, company=company, start_date=start_date, package=package, apply_by=apply_by, job_type=job_type, applied_by=applied_by)
    Recieve_job_applications.objects.create(user=request.user, job=job, resume=resume, resume_file=resumee, apply_for_job=apply_for_job, first_name=first_name, last_name=last_name, email=email, mobile=mobile, position=position, applied_by=applied_by, job_created_by=job_created_by)
    return redirect('home:home_page')

def application_view(request):    
    jobs = Apply_for_job.objects.filter(user = request.user)
    return render(request, 'home/applications.html', {'jobs':jobs})

def applied_jobdeatils_view(request, pk):
    job = Job.objects.filter(pk=pk).first()
    return render(request, 'home/applied_job_detail.html', {'job':job})

def recieve_candidates_applications(request):
    recieve = Recieve_job_applications.objects.filter(job_created_by=request.user)
    return render(request, 'home/recieve_applications.html', {'recieve': recieve})

def update_status(request, pk):
    recieve = Recieve_job_applications.objects.filter(pk=pk)
    recievee = Recieve_job_applications.objects.get(pk=pk) #help .get for getattr() and .filter for update()
    applied_by = getattr(recievee, "applied_by")
    apply = Apply_for_job.objects.filter(applied_by=applied_by)
    if request.method == 'POST':
        status = request.POST['status']
        if status=='Hire':
            recieve.update(status="Hired!")
            apply.update(status="Hired!")
        else:
            recieve.update(status="Rejected!")
            apply.update(status="Rejected!")

    return redirect("home:candidates_applications_view")


def open_resume(request, pk):
    recieve = Recieve_job_applications.objects.get(pk = pk)
    resume = getattr(recieve, 'resume_file')
    response = redirect(f'{resume}')
    return response

home/templates/home/applications.html
{% extends "home/index.html" %}
{% block content %}
<div class="cart">
    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <table class="table table-striped" style="width:1000px">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Position</th>
                        <th scope="col">Company</th>
                        <th scope="col">Job Type</th>
                        <th scope="col">Start date</th>
                        <th scope="col">Package</th>
                        <th scope="col">Apply by</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for j in jobs %}
                    <tr>
                        <td>{{ j.position }}</td>
                        <td>{{ j.company }} </td>
                        <td>{{ j.job_type }}</td>
                        <td>{{ j.start_date }}</td>
                        <td>{{ j.package }} </td>
                        <td>{{ j.apply_by }} </td>
                        <td><a class="btn btn-success" href="{% url 'home:applied_jobdeatils_view' j.id %}">View</a></td>
                    </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/applied_job_detail.html
{% extends 'home/index.html' %}
{% load has_group %}


{% block title %} Job Detail {% endblock title %}

{% block content %}

    <div style="margin-bottom: 20px">
        <!--Main layout-->
        <main class="mt-3 pt-4">
            <div class="container dark-grey-text">
                <div class="row wow fadeIn">
                    <div class="card mb-3" style="height: fit-content; border-radius:15px; width:700px; max-width:fixed;  background-color: #f5f5f5; box-shadow: 0px 0px 1px #000000; padding: 10px 10px 10px 10px">
                        <div class="col">
                            <div style="margin-left: 10px">
                                <h2 style="opacity:97%"><b>{{ job.position }}</b></h2>
                                <h3 style="opacity:80%"><b>{{ job.company }}</b></h3>
                                <label style="margin-right:50px"><b>Start date:</b> {{job.start_date}} &nbsp; &nbsp;</label> 
                                
                                <label style="margin-right:50px"><b>Apply by:</b>{{job.apply_by}} &nbsp; &nbsp;</label> 
                                <label><b>Package:</b>{{job.package}} &nbsp; &nbsp;</label><br>
                                <label><b>{{job.job_type}}</b></label><br>
                                <label ><b>About company:</b></label> 
                                <p style="margin-bottom:10px">{{job.about_company}}<p><br>
                                <label><b>Job description:</b></label>
                                <p style="margin-bottom:10px"> {{job.job_description}}<br>
                                <label><b>Eligibility:</b></label> 
                                <p style="margin-bottom:10px">{{job.eligibility}}</p><br>
                                <label><b>Perks:</b></label> 
                                <p style="margin-bottom:10px">{{job.perks}}</p><br>
                                <label><b>Openings:</b> {{job.openings}} </label><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% if user.is_authenticated %}
                <a href="" class="btn btn-success btn-md my-0 p" style="margin-right:30px; top:10px; margin-left:20px; width:100px; margin-bottom:40px;" disabled>&nbsp; Applied! &nbsp;</a>                
                <a href="{% url 'home:application_view' %}" class="btn btn-secondary btn-md my-2 p" style="  margin-bottom:10px; width:100px">&nbsp; Back &nbsp;</a>
        {% endif %}
        
    </div>
{% endblock content %}

home/templates/home/index.html
{% load has_group %}
{% load static %}
<!doctype html>
<html>
  <head>
    <style type="text/css">
            .sidenav {
                height: 100%;
                width: 180px;
                position: fixed;
                z-index:1;
                top:0;
                left:0;
                background-color:#111;
                overflow-x:hidden;
                padding-top: 20px;
                box-shadow: 0px 5px 10px #000000
            }

            .sidenav a {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                color: #818181;
                display: block;
                font-size: 20px;
                margin-left: 10px
            }

            .sidenav a:hover {
                color:#f5f2d0;
            }

            .main {
                font-family: 'Ubuntu', sans-serif;
                margin-left:15%;
                margin-right:50%
                padding:0px 0px;
                width: fit-content;
            }
            .product .main .container .row img{
                max-width: 540px;
                max-height: 450px;
                width: fit-content;
            }

            .product .main .container .row .content{
                display: flex;
                flex-direction: column;
                text-align: center;
                justify-content: center;
            }

            .product .main .container .row .information{
                display: flex;
                flex-direction: column;
                text-align: center;
                justify-content: center;
            }

      .trow
      {
        margin-right:10px
      }
    </style>
    <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!---Google-font-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="C:\Users\Vinee\Desktop\Autohire\create_resume\static\style.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!---custom-css-->
        <link rel="stylesheet" href="{% static 'css/style.css' %} ">

        <title> {% block title %} My Site {% endblock%}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
  </head>
  <body>
    <div class="sidenav">
        {% comment %} <a  href="/">
            <div class="sidebar-brand-text mx-3" ><img src="../media/logo/logo.png" height="75px"></div>
        </a> {% endcomment %}
        <hr class="sidebar-divider">
        <a href="/"> HOME </a>

        {% comment %} <a href="test/" method='POST'> test </a>   {% endcomment %}

        {% if user.is_authenticated %}
        <li><a href="{% url 'allblog' %}" class="mr-2 text-light">Blog</a></li>
          {% if request.user|has_group:"Employer" %}
            {% comment %} <li><a href="{% url 'home:home_page' %}" class="mr-2 text-light">Profile</a></li> {% endcomment %}
            <li><a href="{% url 'home:addJob' %}" class="mr-2 text-light">Create Jobs</a></li>
            
            <li><a href="{% url 'home:viewJobs' %}" class="mr-2 text-light">View Jobs</a></li>
            <li><a href="{% url 'home:candidates_applications_view' %}" class="mr-2 text-light">Applications</a></li>
            {% comment %} <li><a href="{% url 'home:home_page' %}" class="mr-2 text-light">Hired</a></li> {% endcomment %}
          {% elif request.user|has_group:"Candidate" %}
            {% comment %} <li><a href="{% url 'home:home_page' %}" class="mr-2 text-light">Profile</a></li> {% endcomment %}
            <li><a href="{% url 'create_resume:resume'  %}" class="mr-2 text-light">My Resume</a></li>
            <li><a href="{% url 'home:application_view'  %}" class="mr-2 text-light">Applications</a></li>
          {% endif %}

          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" style="margin-left:20px; ">Logout</button>
            </form>
          </li> 
                
        {% else %}
          <li><a href="{% url 'accounts:log_in' %}" class="mr-2 text-light">Login</a></li>
          <li><a href="{% url 'accounts:candidate_sign_up' %}" class="mr-2 text-light">Looking for jobs?</a></li>
          <li><a href="{% url 'accounts:employer_sign_up' %}" class="mr-2 text-light">Want to hire?</a></li>
        {% endif %}
        </ul> 
    </div>
    
    <div id="content", name="content", class="main">
      <div class="row justify-content-center">
        <div class="col-8">
          <!-- <h1 class="mt-2"> WELCOME TO Auto-Hire </h1> -->
          <hr class="mt-0 mb-4">
        </div>
        <div style='margin-left:50px'>
          {% block content %}
              Home
          {% endblock %}
        </div>
      </div>  
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/job_detail.html
{% extends 'home/index.html' %}
{% load has_group %}


{% block title %} Job Detail {% endblock title %}

{% block content %}

    <div style="margin-bottom: 20px">
        <!--Main layout-->
        <main class="mt-3 pt-4">
            <div class="container dark-grey-text">
                <div class="row wow fadeIn">
                    <div class="card mb-3" style="height: fit-content; border-radius:15px; width:700px; max-width:fixed;  background-color: #f5f5f5; box-shadow: 0px 0px 1px #000000; padding: 10px 10px 10px 10px">
                        <div class="col">
                            <div style="margin-left: 10px">
                                <h2 style="opacity:97%"><b>{{ job.position }}</b></h2>
                                <h3 style="opacity:80%"><b>{{ job.company }}</b></h3>
                                <label style="margin-right:50px"><b>Start date:</b> {{job.start_date}} &nbsp; &nbsp;</label> 
                                
                                <label style="margin-right:50px"><b>Apply by:</b>{{job.apply_by}} &nbsp; &nbsp;</label> 
                                <label><b>Package:</b>{{job.package}} &nbsp; &nbsp;</label><br>
                                <label><b>{{job.job_type}}</b></label><br>
                                <label ><b>About company:</b></label> 
                                <p style="margin-bottom:10px">{{job.about_company}}<p><br>
                                <label><b>Job description:</b></label>
                                <p style="margin-bottom:10px"> {{job.job_description}}<br>
                                <label><b>Eligibility:</b></label> 
                                <p style="margin-bottom:10px">{{job.eligibility}}</p><br>
                                <label><b>Perks:</b></label> 
                                <p style="margin-bottom:10px">{{job.perks}}</p><br>
                                <label><b>Openings:</b> {{job.openings}} </label><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% if user.is_authenticated %}
            {% if request.user|has_group:"Candidate" %}
                    <a href="{% url 'home:apply_for_job' id %}" class="btn btn-success btn-md my-0 p" style="margin-right:30px; top:10px; margin-left:20px; width:100px; margin-bottom:40px;">&nbsp; Apply &nbsp;</a>
                    <a href="" class="btn btn-primary btn-md my-0 p" style="margin-right:10px; margin-bottom:10px; width:100px">&nbsp; Save &nbsp;</a>
                {% endif %}
                
                <a href="{% url 'home:home_page' %}" class="btn btn-secondary btn-md my-2 p" style="  margin-bottom:10px; width:100px">&nbsp; Back &nbsp;</a>
            {% endif %}
        
    </div>
{% endblock content %}

home/templates/home/recieve_applications.html
{% extends "home/index.html" %}
{% block content %}
<div class="cart">
    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <table class="table table-striped" style="width:1000px">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">First name</th>
                            <th scope="col">Last name</th>
                            <th scope="col">Phone number</th>
                            <th scope="col">Email</th>
                            <th scope="col">Position</th>
                            <th scope="col">Resume</th>
                            <th scope="col">Status</th>
                            <th scope="col">Update status</th>
                            {% comment %} <th scope="col"></th> {% endcomment %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for j in recieve %}
                            <tr>
                                <td>{{ j.first_name }}</td>
                                <td>{{ j.last_name }} </td>
                                <td>{{ j.mobile }}</td>
                                <td>{{ j.email }}</td>
                                <td>{{j.position}}</td>
                                <td><a href="{% url 'home:open_resume' j.id %}">{{j.resume_file}}</a></td>
                                <td>{{j.status}}</td>
                                <td>
                                    <form method="POST" action="{% url 'home:update_status' j.id %}" style="display: flex;">
                                        {% csrf_token %}
                                        <select class="form-control" name="status" style="width:110px; margin-right:10px">
                                            <option value="Hire" selected="selected">Hired</option>
                                            <option value="Reject">Rejected</option>
                                        </select>
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/home/test.html
{% extends 'home/index.html' %}

{% block title %} test {% endblock title %} 

{% block content %}

<h2>Welcome, <small>{{ user.username }}</small>!</h2>
<p>Your email address: {{ user.email }}</p>
<p>Department: {{ userr }}</p>
<p>Department: {{ user }}</p>
{% for j in job  %}
<p>Department: {{ j.id }}</p>
{% endfor %}

{% endblock content %}