Autohire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('user/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls')),

    path('create_resume/', include('create_resume.urls', namespace='create_resume'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import addblog,home_screen_view,detail_blog_view

urlpatterns = [
    path('post/', addblog,name="addblog"),
    path('allblog/',home_screen_view,name="allblog"),
    path('allblog/<pk>', detail_blog_view, name="detailblog"),
] 

create_resume/urls.py
from django.urls import path
from . import views
from .views import (
    IdentityUpdateView,
    # create
    QualificationsCreateView,
    ExperienceCreateView,
    InternshipCreateView,
    CertificationsCreateView,
    ProjectsCreateView,
    Technical_skillsCreateView,
    # delete
    ExperienceDeleteView,
)

app_name = 'create_resume'
urlpatterns = [
    path('resume/',views.resume, name='resume'),
    path('identity-update/', IdentityUpdateView.as_view(), name='update-identity'),
    
    # create
    path('create-qualifications/', QualificationsCreateView.as_view(), name='create-qualifications' ),
    path('create-experience/', ExperienceCreateView.as_view(), name='create-experience' ),
    path('create-internship/', InternshipCreateView.as_view(), name='create-internship'),
    path('create-certification/', CertificationsCreateView.as_view(), name='create-certifications'),
    path('create-project/', ProjectsCreateView.as_view(), name='create-projects'),
    path('create-technical-skill/', Technical_skillsCreateView.as_view(), name='create-technical-skills'),
    
    #delete
    path('delete-experience/<int:pk>', ExperienceDeleteView.as_view(), name='delete-experience')
] 

create_resume/models.py
from django.db import models
from django.db.models.base import Model
from home.models import User
from django.shortcuts import reverse

# Create your models here.
class Identity(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # personal information
    name = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)
    phone_number = models.CharField(max_length=13, null=True)
    address = models.CharField(max_length=300, null=True)
    
    def get_absolute_url(self):
        return reverse("create_resume:resume", kwargs={"pk": self.pk})
    
    def get_update_identity_url(self):
        return reverse("create_resume:update-identity", kwargs={'pk': self.pk})
    
    
# Experience
class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    position = models.CharField(max_length=200, null=True)
    location = models.CharField(max_length=200, null=True)
    duration = models.CharField(max_length=100, null=False)
    # ongoing = models.BooleanField(default=False)
    desc = models.TextField(null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse("create_resume:resume", kwargs={})
    
    def get_delete_url(self):
        return reverse('create_resume:resume', kwargs={'pk':self.pk})

# Internship    
class Internship(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name  = models.CharField(max_length=200, null=True)
    position = models.CharField(max_length=200, null=True)
    duration = models.CharField(null=False, max_length=100)
    # ongoing = models.BooleanField(default=False)
    location = models.CharField(max_length=200, null=True)
    desc = models.TextField(null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse("create_resume:resume", kwargs={})

# Qulaifications

class Qualifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    location = models.CharField(max_length=200, null=True)
    degree = models.CharField(max_length=100, null=True)
    branch = models.CharField(max_length=200, null=True)
    duration = models.CharField(null=False, max_length=100)
    # ongoing = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("create_resume:resume", kwargs={})
    
    
    # def get_absolute_url(self):
    #     return reverse("create_resume:create-qualifications", kwargs={})
    

# class Masters(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     masters_university_name = models.CharField(max_length=100, null=True)
#     masters_university_location = models.CharField(max_length=200, null=True)
#     masters_degree = models.CharField(max_length=100, null=True)
#     masters_branch = models.CharField(max_length=200, null=True)
#     masters_degree_duration = models.DurationField()
#     master_pursuing = models.BooleanField(default=False)

# class Bachelors(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     bachelors_university_name = models.CharField(max_length=100, null=True)
#     bachelors_university_location = models.CharField(max_length=200, null=True)
#     bachelors_degree = models.CharField(max_length=100, null=True)
#     bachelors_branch = models.CharField(max_length=200, null=True)
#     bachelors_degree_duration = models.DurationField()
#     bachelors_pursuing = models.BooleanField(default=False)
    
# class High_school(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     school_name = models.CharField(max_length=200, null=True)
#     school_location = models.CharField(max_length=200, null=True)
#     class_name = models.CharField(max_length=200, null=True)
#     branch = models.CharField(max_length=200, null=True)
#     class_duration = models.DurationField()
    
# Certifications
class Certifications(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE) 
   name = models.CharField(max_length=200, null=True)
   company = models.CharField(max_length=200, null=True)
   duration = models.CharField(null=False, max_length=100)
   desc = models.TextField(null=True, blank=True)
   
   def get_absolute_url(self):
       return reverse("create_resume:resume", kwargs={})
   
    

# Projects
class Projects(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    duration = models.CharField(null=False, max_length=100)
    # ongoing = models.BooleanField(default=False)
    desc = models.TextField(null=True, blank=True)
    link = models.URLField(max_length=200, null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse("create_resume:resume", kwargs={})
    
# skills
class Technical_skills(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    skill = models.CharField(max_length=200, null=True)
    expertise = models.CharField(max_length=100, null=True)  
    
    def get_absolute_url(self):
        return reverse("create_resume:resume", kwargs={}) 
   

create_resume/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.views.generic.edit import DeleteView, UpdateView

from home.models import Resume
from .models import *

# Create your views here.

def resume(request): #removed user
    user = request.user
    resume = Resume.objects.get(user=user)
    qualifications = Qualifications.objects.filter(user=user)
    experience = Experience.objects.filter(user=user)
    internship = Internship.objects.filter(user=user)
    certification = Certifications.objects.filter(user=user)
    project = Projects.objects.filter(user=user)
    technical_skill = Technical_skills.objects.filter(user=user)
    context = {
        'user':user,
        'resume':resume,
        'qualifications':qualifications,
        'experience':experience,
        'internship':internship,
        'certification':certification,
        'project':project,
        'technical_skill':technical_skill,
    }
    
    # To save Identity
    # name = getattr(user, 'first_name') + " " + getattr(user, 'last_name')
    # email = getattr(user, 'email')
    # phone_number = getattr(resume, 'mobile')
    # address = getattr(resume, 'address')
    # Identity.objects.create(user=user, name=name, email=email, phone_number=phone_number, address=address)
    
    return render(request, 'create_resume/resume.html', context)

# Create forms
class ExperienceCreateView(CreateView):
    model = Experience
    fields = ['name', 'position', 'location', 'duration', 'desc']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class InternshipCreateView(CreateView):
    model = Internship
    fields = ['name', 'position', 'location', 'duration', 'desc']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class QualificationsCreateView(CreateView):
    model = Qualifications
    fields = ['name', 'location', 'degree', 'branch', 'duration']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class CertificationsCreateView(CreateView):
    model = Certifications
    fields = ['name', 'company', 'duration', 'desc']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ProjectsCreateView(CreateView):
    model = Projects
    fields = ['name', 'duration', 'desc', 'link']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class Technical_skillsCreateView(CreateView):
    model = Technical_skills
    fields = ['skill', 'expertise']
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# Update forms    
class IdentityUpdateView( UpdateView):
    model = Identity
    fields = ['name', 'email', 'phone_number', 'address']

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def test_func(self):
        identity = self.get_object()
        if self.request.user == identity.user:
            return True
        return False

# Delete data

class ExperienceDeleteView(DeleteView):
    model = Experience
    success_url = '/resume/'

    def test_func(self):
        experience = self.get_object()
        if self.request.user == experience.user:
            return True
        return False
    
# class IdentityDeleteView(DeleteView):
#     model = Identity
#     # success_url = '/item_list'

#     def test_func(self):
#         identity = self.get_object()
#         if self.request.user == identity.user:
#             return True
#         return False


# class IdentityUpdateView(UpdateView):
#     model = Identity
#     fields = ['name', 'email', 'phone_number', 'address']
#     # success_url = "create_resume/resume/"
    
#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         return super().form_valid(form)

create_resume/templates/create_resume/certifications_form.html
{% extends 'home/index.html' %}

{% block title %} Add Qualifications {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add Certification</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

create_resume/templates/create_resume/experience_form.html
{% extends 'home/index.html' %}

{% block title %} Add Experience {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add Experience</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

create_resume/templates/create_resume/identity_form.html
{% extends 'home/index.html' %}

{% block title %} Identity {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

create_resume/templates/create_resume/internship_form.html
{% extends 'home/index.html' %}

{% block title %} Internship {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add Internship</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

create_resume/templates/create_resume/projects_form.html
{% extends 'home/index.html' %}

{% block title %} Add Qualifications {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add Project</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

create_resume/templates/create_resume/qualifications_form.html
{% extends 'home/index.html' %}

{% block title %} Add Qualifications {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add Qualification</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

create_resume/templates/create_resume/resume.html
{% extends "home/index.html" %}
{% load static %}
{% block title %} My Resume {% endblock title %}

{% block content %}

    <div class="main-container" style="background:rgb(247, 247, 247);">
        <div class="top-container">
            <div class = "top-container-name name-spacing">
                <h2>{{user.first_name }}&nbsp;{{ user.last_name}}</h2>
            </div>
            <div class = "top-container-address spaceing">
                <p class="gmail">{{user.email}}</p>
                <p class="number">+91 {{resume.mobile}}</p>
                <p class="address">{{resume.address}}</p>
            </div>
            <div class = "top-container-download end-spacing">
                {% comment %} <a href="#"><i class="fa fa-download">Download</i></i></a><br><br> {% endcomment %}
                {% comment %} <a class="edit" href="{% url 'create_resume:update-identity' %}"><i class="fa fa-edit"></i></a> {% endcomment %}
                {% comment %} <a class="delete" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>
        </div>
        <div class="top-container">
            <div class = "top-container-education name-spacing">
                <p><b>QUALIFICATIONS</b></p>
            </div>
            <div class = "top-container-education-detail spaceing ">
                {% for q in qualifications %}
                    <p class="degree"><b>{{q.name}} &nbsp; {{q.location}}</b> 
                    {% comment %} <a class="edit links" href="#"><i class="fa fa-edit"></i></a>
                    <a class="delete links" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
                    </p>
                    <p class="duration">{{q.degree}} &nbsp; {{q.branch}}</p>
                    <p class="duration">{{q.duration}}</p>
                {% endfor %}
                <a class="Add button"href="{% url 'create_resume:create-qualifications' %}"><spam> + </spam> Add qualification </a>
            </div>
            <div class = "top-container-download end-spacing">
                {% comment %} <a class="edit" href="#"><i class="fa fa-edit"></i></a>
                <a class="delete" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>
        </div>
        <div class="top-container">
            <div class = "top-container-jobs name-spacing">
                <p><b>Experience</b></p>
            </div>
            <div class = "top-container-jobs-detail spaceing">
                {% for e in experience %}
                    <p><b>{{e.name}}</b></p>
                    <p><b>{{e.position}}</b></p>
                    <p>{{e.location}} &nbsp;  {{e.duration}}</p>
                    <p></p>
                    <p>{{e.desc}}</p>
                {% endfor %}
                <a class="Add button"href="{% url 'create_resume:create-experience' %}"><spam> + </spam> Add job </a>
            </div>
            <div class = "top-container-download end-spacing">
                {% comment %} <a class="edit" href="#"><i class="fa fa-edit"></i></a>
                <a class="delete" href="{% url 'create_resume:delete-experience' e.id %}"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>  
        </div>
        <div class="top-container">
            <div class = "top-container-internship name-spacing">
            <p><b>INTERNSHIPS</b></p>
            </div>
                <div class = "top-container-internship-detail spaceing">
                    {% for i in internship %}
                        <p>{{i.name}}</p>
                        <p><b>{{i.position}}</b></p>
                        <p>{{i.location}} &nbsp;  {{i.duration}}</p>
                        <p></p>
                        <p>{{i.desc}}</p>
                    {% endfor %}
                    <a class="Add button"href="{% url 'create_resume:create-internship' %}"><spam> + </spam> Add internship </a>
                </div>
            <div class = "top-container-download end-spacing">
            {% comment %} <a class="edit" href="#"><i class="fa fa-edit"></i></a>
            <a class="delete" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>
        </div>
        <div class="top-container">
            <div class = "top-container-training name-spacing">
            <p><b>CERTIFICATIONS</b></p>
            </div>
            <div class = "top-container-training-detail spaceing">
                {% for c in certification %}
                    <p>{{c.name}}</p>
                    <p><b>{{c.company}}</b></p>
                    <p>{{c.duration}}</p>
                    <p></p>
                    <p>{{c.desc}}</p>
                {% endfor %}
            <a class="Add button"href="{% url 'create_resume:create-certifications' %}"><spam> + </spam> Add Certification </a>
            </div>
            <div class = "top-container-download end-spacing">
            {% comment %} <a class="edit" href="#"><i class="fa fa-edit"></i></a>
            <a class="delete" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>
        </div>
        <div class="top-container">
            <div class = "top-container-project name-spacing">
            <p><b>PROJECTS</b></p>
            </div>
            <div class = "top-container-project-detail spaceing">
                {% for p in project %}
                    <p>{{p.name}}</p>
                    <p><b>{{p.duration}}</b></p>
                    <p> {{p.desc}}</p>
                    <p></p>
                    <p>{{p.link}}</p>
                {% endfor %}
            <a class="Add button"href="{% url 'create_resume:create-projects' %}"><spam> + </spam> Add Project </a>
            </div>
            <div class = "top-container-download end-spacing">
            {% comment %} <a class="edit" href="#"><i class="fa fa-edit"></i></a>
            <a class="delete" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>
        </div>
        <div class="top-container">
            <div class = "top-container-skills name-spacing">
            <p><b>TECHNICAL SKILLS</b></p>
            </div>
            <div class = "top-container-skills-detail spaceing">
                {% for t in technical_skill %}
                    <p>{{t.skill}}</p>
                    <p>{{t.expertise}}</p>
                {% endfor %}
            
            <a class="Add button"href="{% url 'create_resume:create-technical-skills' %}"><spam> + </spam> Add Technical Skill </a>
            </div>
            <div class = "top-container-download end-spacing">
            {% comment %} <a class="edit" href="#"><i class="fa fa-edit"></i></a>
            <a class="delete" href="#"><i class="fa fa-trash"></i></a> {% endcomment %}
            </div>
        </div>
        
    </div>
        
{% endblock content %}

create_resume/templates/create_resume/technical_skills_form.html
{% extends 'home/index.html' %}

{% block title %} Add Qualifications {% endblock title %}

{% load crispy_forms_tags %}

{% block content %}

<div class="form">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group" style='width:600px'>
                        <legend class="border-bottom mb-4">Add Technical skill</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}