Autohire/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('user/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls')),

    path('create_resume/', include('create_resume.urls', namespace='create_resume'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import addblog,home_screen_view,detail_blog_view

urlpatterns = [
    path('post/', addblog,name="addblog"),
    path('allblog/',home_screen_view,name="allblog"),
    path('allblog/<pk>', detail_blog_view, name="detailblog"),
] 

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class BlogPost(models.Model):
    title=models.CharField( max_length=50)
    body=models.TextField(max_length=5000)
    picture=models.ImageField(upload_to='blogpicture/')
    created_on=models.DateTimeField( auto_now_add=True)
    updated_on=models.DateTimeField( auto_now=True)
    author=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comment(models.Model):
    blog=models.ForeignKey(BlogPost,on_delete=models.CASCADE)
    comment_by=models.ForeignKey(User, on_delete=models.CASCADE)
    comment=models.TextField(max_length=100)
    def __str__(self):
        return self.blog.title
    
class Like(models.Model):
    blog=models.ForeignKey(BlogPost,on_delete=models.CASCADE)
    liked_by=models.ForeignKey(User, on_delete=models.CASCADE)
    like=models.BooleanField(default=True)

    def __str__(self):
        return self.blog.title

blog/forms.py
from django.forms import ModelForm,forms
from .models import *
# from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput
from bootstrap_datepicker_plus.widgets import DateTimePickerInput,TimePickerInput


class AddBlogForm(ModelForm):
	class Meta:
		model = BlogPost
		fields = ['title','body','picture',]

class AddCommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = ['comment']

blog/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .forms import AddBlogForm,AddCommentForm
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

# from .views import get_blog_queryset
from .models import BlogPost

BLOG_POSTS_PER_PAGE = 10
# Create your views here.

@csrf_exempt
def addblog(request):
    context = {}
    user = request.user
    if  user.is_authenticated:
        form = AddBlogForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            obj = form.save(commit=False)
            author = User.objects.filter(id=user.id).first()
            obj.author = author
            obj.save()
            form = AddBlogForm()

            context['form'] = form

    return render(request, "blog/addblog.html", context)

def detail_blog_view(request, pk):

	context = {}

	blog_post = get_object_or_404(BlogPost, pk=pk)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail_blog.html', context)


def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))

def home_screen_view(request, *args, **kwargs):
	
	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset(query), key=attrgetter('updated_on'), reverse=True)
	


	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "blog/allblog.html", context)

blog/templates/blog/addblog.html
{% extends 'home/index.html' %}
{% load static %}
{% block title %}
    Add Blog
{% endblock title %}

{% block content %}
    

<style type="text/css">
    .create-form {
          width: 100%;
          max-width: 100%;
          padding: 25px;
          margin: auto;
        }
  
        .submit-button{
            max-width: 200px;
        }
        .main{
            width: 60%;
        }
  </style>
  
  <div class="container">
      <div class="row">
          <div class="col-lg-12 offset-lg-1 ">
            <h1 class="mt-2"> Add Blog </h1>

              <form class="create-form " method="post" enctype="multipart/form-data">
                {% csrf_token %}
  
                  <!-- title -->
                  <div class="form-group">
                      <label for="id_title">Title</label>
                      <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                  </div>
  
                  <!-- Body -->
                  <div class="form-group">
                      <label for="id_body">Content</label>
                      <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This blog is about..." required></textarea>
                  </div>
  
                  <!-- Image -->
                  <div class="form-group">
                      <label for="id_image">Image</label>
                      <input  type="file" name="picture" id="id_image" accept="image/*" required>
                  </div>
  
                  <!-- Submit btn -->
                  <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
              </form>	
          </div>
      </div>
  </div>
    

{% endblock content %}
    
    

blog/templates/blog/allblog.html
{% extends 'home/index.html' %}
{% load static %}
{% block title %}
    All Blog
{% endblock title %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<p class="lead">Connect to the world ,Share your own Blogs.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'addblog' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'icon.jpg' %}" width="72" height="72">
				<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
  					framework and you'll see why in this course.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'addblog' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->



	</div>
</div>

    
{% endblock content %}
    
    

blog/templates/blog/detail_blog.html
{% extends 'home/index.html' %}

{% block title %}
Detail
    
{% endblock title %}

{% block content %}


<style type="text/css">
	.card{
		max-width: 700px;
	}
	.card-body{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{blog_post.picture.url}}">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{blog_post.title}}</h2>
			  <p class="card-text">{{blog_post.body|safe}}</p>
		
			</div>
			<div class="card-footer text-muted">
			  Updated on {{blog_post.updated_on}} by {{blog_post.author}}
			</div>
		</div>
	</div>
</div>

	

{% endblock content %}

    
    